### ISSUE TITLE
The pretrained model's  link is ineffective.

### ISSUE THREAD

**Issue by jinlian152** [HyeongseokSon1/natural_image_tone_enhancement#4]
https://drive.google.com/open?id=1oN6501xXOpJHqPZCdkQ52IUcrjuEzYob 404 now.

**Comment by HyeongseokSon1** [comment]
Thanks for your interest in our work.
We have updated a new link.
https://drive.google.com/file/d/1pJuRM_xPOXKmcpJgKa889l1gzM5zCVRl/view?usp=sharing
